name: Docker alpine images build

on:
  push:
    branches: ['*']
  schedule:
    - cron: '0 0 1 * *'

## ref: https://docs.github.com/en/actions/examples/using-concurrency-expressions-and-a-test-matrix
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  docker-systemd-alpine:
    runs-on: ubuntu-latest
#    concurrency:
#      group: ${{ github.workflow }}-{{ github.job }}-${{ github.ref }}
#      cancel-in-progress: true
    strategy:
      matrix:
        include:
          - name: openrc-alpine
            dockerfile: openrc/alpine/Dockerfile
            platforms: |-
              linux/amd64
            tags: |-
              lj020326/openrc-alpine:latest
          - name: aports-dev
            dockerfile: aports-dev/Dockerfile
            platforms: |-
              linux/amd64
            tags: |-
              lj020326/aports-dev:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: lj020326
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platforms }}
          push: true
          tags: ${{ matrix.tags }}
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.revision=${{ github.sha }}

  docker-systemd-python-alpine:
    runs-on: ubuntu-latest
    needs: docker-systemd-alpine
#    concurrency:
#      group: ${{ github.workflow }}-{{ github.job }}-${{ github.ref }}
#      cancel-in-progress: true
    strategy:
      matrix:
        include:
          - name: openrc-alpine-python
            dockerfile: openrc/alpine/python.Dockerfile
            platforms: |-
              linux/amd64
            tags: |-
              lj020326/openrc-alpine-python:latest
          - name: aports-dev-python
            dockerfile: aports-dev/python.Dockerfile
            platforms: |-
              linux/amd64
            tags: |-
              lj020326/aports-dev-python:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: lj020326
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platforms }}
          push: true
          tags: ${{ matrix.tags }}
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.revision=${{ github.sha }}
