name: Docker alpine images build

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      platforms:
        required: true
        type: string
      tags:
        required: true
        type: string

#    secrets:
#      envPAT:
#        required: true

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: lj020326
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push ${{ inputs.name }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          platforms: ${{ inputs.platforms }}
          push: true
          tags: ${{ inputs.tags }}
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.revision=${{ github.sha }}
