name: Docker redhat images build

on:
  push:
    branches: ['*']
  schedule:
    - cron: '0 0 1 * *'

## ref: https://docs.github.com/en/actions/examples/using-concurrency-expressions-and-a-test-matrix
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  docker-systemd-redhat:
    runs-on: ubuntu-latest
#    concurrency:
#      group: ${{ github.workflow }}-{{ github.job }}-${{ github.ref }}
#      cancel-in-progress: true
    strategy:
      matrix:
        include:
          - name: systemd-redhat7
            dockerfile: systemd/redhat/7.Dockerfile
            context: .
            platforms: |-
              linux/amd64
            tags: |-
              lj020326/redhat7-systemd:latest
          - name: systemd-redhat8
            dockerfile: systemd/redhat/8.Dockerfile
            context: .
            platforms: |-
              linux/amd64
              linux/arm64
            tags: |-
              lj020326/redhat8-systemd:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: lj020326
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platforms }}
          push: true
          tags: ${{ matrix.tags }}
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.revision=${{ github.sha }}

  docker-systemd-python-redhat:
    runs-on: ubuntu-latest
    needs: docker-systemd-redhat
#    concurrency:
#      group: ${{ github.workflow }}-{{ github.job }}-${{ github.ref }}
#      cancel-in-progress: true
    strategy:
      matrix:
        include:
          - name: systemd-redhat7-python
            dockerfile: systemd/redhat/7.python.Dockerfile
            context: systemd/redhat
            platforms: |-
              linux/amd64
            tags: |-
              lj020326/redhat7-systemd-python:latest
          - name: systemd-redhat8-python
            dockerfile: systemd/redhat/8.python.Dockerfile
            context: systemd/redhat
            platforms: |-
              linux/amd64
              linux/arm64
            tags: |-
              lj020326/redhat8-systemd-python:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: lj020326
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platforms }}
          push: true
          tags: ${{ matrix.tags }}
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.revision=${{ github.sha }}
