name: Docker alpine images build

on:
  push:
    branches: ['*']
#  schedule:
#    - cron: '30 0 1 * *'

jobs:
  docker-systemd-alpine:
    runs-on: ubuntu-latest

#    ## ref: https://docs.github.com/en/actions/examples/using-concurrency-expressions-and-a-test-matrix
#    concurrency:
#      group: ${{ github.workflow }}-systemd-alpine-${{ github.ref }}
##      cancel-in-progress: true
#      cancel-in-progress: false

    strategy:
      fail-fast: false
      ## ref: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
#      max-parallel: 2
      matrix:
        include:
          - distro: alpine
            systemd-distro:
              name: openrc-alpine
              dockerfile: openrc/alpine/Dockerfile
              context: .
              platforms: |-
                linux/amd64
              tags: |-
                lj020326/openrc-alpine:latest
            systemd-python-distro:
              name: openrc-alpine-python
              dockerfile: openrc/alpine/python.Dockerfile
              context: .
              platforms: |-
                linux/amd64
              tags: |-
                lj020326/openrc-alpine-python:latest

          - distro: aports-dev
            systemd-distro:
              name: aports-dev
              dockerfile: aports-dev/Dockerfile
              context: .
              platforms: |-
                linux/amd64
              tags: |-
                lj020326/aports-dev:latest
            systemd-python-distro:
              name: aports-dev-python
              dockerfile: aports-dev/python.Dockerfile
              context: .
              platforms: |-
                linux/amd64
              tags: |-
                lj020326/aports-dev-python:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: lj020326
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push ${{ matrix.systemd-distro.name }}
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.systemd-distro.context }}
          file: ${{ matrix.systemd-distro.dockerfile }}
          platforms: ${{ matrix.systemd-distro.platforms }}
          push: true
          tags: ${{ matrix.systemd-distro.tags }}
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build and push ${{ matrix.systemd-python-distro.name }}
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.systemd-python-distro.context }}
          file: ${{ matrix.systemd-python-distro.dockerfile }}
          platforms: ${{ matrix.systemd-python-distro.platforms }}
          push: true
          tags: ${{ matrix.systemd-python-distro.tags }}
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.revision=${{ github.sha }}
