name: Docker debian images build

on:
  push:
    branches: ['*']
#  schedule:
#    - cron: '30 0 1 * *'

### ref: https://docs.github.com/en/actions/examples/using-concurrency-expressions-and-a-test-matrix
#concurrency:
#  group: ${{ github.workflow }}-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
#  cancel-in-progress: true

jobs:
  docker-systemd-debian:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-systemd-${{ github.ref }}
#      cancel-in-progress: true
      cancel-in-progress: false

    strategy:
      fail-fast: false
      ## ref: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
      max-parallel: 2
      matrix:
        include:
          - distro: debian8
            systemd-distro:
              name: systemd-debian8
              dockerfile: systemd/debian/8.Dockerfile
              platforms: |-
                linux/amd64
              tags: |-
                lj020326/debian8-systemd:latest
            systemd-python-distro:
              name: systemd-debian8-python
              dockerfile: systemd/debian/8.python.Dockerfile
              platforms: |-
                linux/amd64
              tags: |-
                lj020326/debian8-systemd-python:latest

          - distro: debian9
            systemd-distro:
              name: systemd-debian9
              dockerfile: systemd/debian/9.Dockerfile
              platforms: |-
                linux/amd64
                linux/arm/v7
                linux/arm64
              tags: |-
                lj020326/debian9-systemd:latest
            systemd-python-distro:
              name: systemd-debian9-python
              dockerfile: systemd/debian/9.python.Dockerfile
              platforms: |-
                linux/amd64
                linux/arm/v7
                linux/arm64
              tags: |-
                lj020326/debian9-systemd-python:latest

          - distro: debian10
            systemd-distro:
              name: systemd-debian10
              dockerfile: systemd/debian/10.Dockerfile
              platforms: |-
                linux/amd64
                linux/arm/v7
                linux/arm64
              tags: |-
                lj020326/debian10-systemd:latest
            systemd-python-distro:
              name: systemd-debian10-python
              dockerfile: systemd/debian/10.python.Dockerfile
              platforms: |-
                linux/amd64
                linux/arm/v7
                linux/arm64
              tags: |-
                lj020326/debian10-systemd-python:latest

          - distro: debian11
            systemd-distro:
              name: systemd-debian11
              dockerfile: systemd/debian/11.Dockerfile
              platforms: |-
                linux/amd64
                linux/arm/v7
                linux/arm64
              tags: |-
                lj020326/debian11-systemd:latest
            systemd-python-distro:
              name: systemd-debian11-python
              dockerfile: systemd/debian/11.python.Dockerfile
              platforms: |-
                linux/amd64
                linux/arm/v7
                linux/arm64
              tags: |-
                lj020326/debian11-systemd-python:latest

          - distro: debian12
            systemd-distro:
              name: systemd-debian12
              dockerfile: systemd/debian/12.Dockerfile
              platforms: |-
                linux/amd64
                linux/arm/v7
                linux/arm64
              tags: |-
                lj020326/debian12-systemd:latest
            systemd-python-distro:
              name: systemd-debian12-python
              dockerfile: systemd/debian/12.python.Dockerfile
              platforms: |-
                linux/amd64
                linux/arm/v7
                linux/arm64
              tags: |-
                lj020326/debian12-systemd-python:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: lj020326
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push ${{ matrix.systemd-distro.name }}
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ matrix.systemd-distro.dockerfile }}
          platforms: ${{ matrix.systemd-distro.platforms }}
          push: true
          tags: ${{ matrix.systemd-distro.tags }}
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build and push ${{ matrix.systemd-python-distro.name }}
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ matrix.systemd-python-distro.dockerfile }}
          platforms: ${{ matrix.systemd-python-distro.platforms }}
          push: true
          tags: ${{ matrix.systemd-python-distro.tags }}
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.revision=${{ github.sha }}
