name: Docker redhat images build

on:
  push:
    branches: ['*']
#  schedule:
#    - cron: '30 0 1 * *'

### ref: https://docs.github.com/en/actions/examples/using-concurrency-expressions-and-a-test-matrix
#concurrency:
#  group: ${{ github.workflow }}-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
#  cancel-in-progress: true

jobs:
  docker-systemd-redhat:
    runs-on: ubuntu-latest

#    concurrency:
#      group: ${{ github.workflow }}-systemd-${{ github.ref }}
##      cancel-in-progress: true
#      cancel-in-progress: false

    strategy:
      fail-fast: false
      ## ref: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
#      max-parallel: 2
      matrix:
        include:
          - distro: redhat7
            systemd-distro:
              name: systemd-redhat7
              dockerfile: systemd/redhat/7.Dockerfile
              context: .
              platforms: |-
                linux/amd64
              tags: |-
                lj020326/redhat7-systemd:latest
            systemd-python-distro:
              name: systemd-redhat7-python
              dockerfile: systemd/redhat/7.python.Dockerfile
              context: systemd/redhat
              platforms: |-
                linux/amd64
              tags: |-
                lj020326/redhat7-systemd-python:latest

          - distro: redhat8
            systemd-distro:
              name: systemd-redhat8
              dockerfile: systemd/redhat/8.Dockerfile
              context: .
              platforms: |-
                linux/amd64
                linux/arm64
              tags: |-
                lj020326/redhat8-systemd:latest
            systemd-python-distro:
              name: systemd-redhat8-python
              dockerfile: systemd/redhat/8.python.Dockerfile
              context: systemd/redhat
              platforms: |-
                linux/amd64
                linux/arm64
              tags: |-
                lj020326/redhat8-systemd-python:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: lj020326
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push ${{ matrix.systemd-distro.name }}
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ matrix.systemd-distro.dockerfile }}
          platforms: ${{ matrix.systemd-distro.platforms }}
          push: true
          tags: ${{ matrix.systemd-distro.tags }}
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build and push ${{ matrix.systemd-python-distro.name }}
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.systemd-python-distro.context }}
          file: ${{ matrix.systemd-python-distro.dockerfile }}
          platforms: ${{ matrix.systemd-python-distro.platforms }}
          push: true
          tags: ${{ matrix.systemd-python-distro.tags }}
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.revision=${{ github.sha }}
